server:
  port: 8070

spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/db1803
        username: root
        password: root

mybatis:
  mapUnderscoreToCamelCase: true
  typeAliasesPackage: com.let.pojo
  mapperLocations: classpath:mappers/*.xml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  

logging:
  level: 
    com.let.mapper: debug
   